#!/usr/bin/env bash

SNAME="donor-match"

function kill-session {
  if tmux ls 2>&1 | grep -q "^${SNAME}:"; then
    tmux kill-session -t "$SNAME"
  fi
}

kill-session

tmux new-session -d -s "$SNAME" -n "app"     -c "$(pwd)/packages/app"     "bun run dev"
tmux new-window     -t "$SNAME" -n "api"     -c "$(pwd)/packages/api"     "bun run build && bun run dev"
tmux new-window     -t "$SNAME" -n "db"      -c "$(pwd)/packages/db"      "bun run build && bun run schema:gen && bun run schema:push && bun run seed; exec zsh -c 'cd \"$(pwd)/packages/db\" && exec zsh -l'"
tmux new-window     -t "$SNAME" -n "ts-rest" -c "$(pwd)/packages/ts-rest" "bun run build; exec zsh -c 'cd \"$(pwd)/packages/ts-rest\" && exec zsh -l'"

tmux select-window -t "$SNAME:0"
tmux attach-session -t "$SNAME"

kill-session
