packages:
  - apps/*
  - packages/*

catalog:
  dmno: latest
  eslint: latest
  prettier: latest
  tailwindcss: latest
  typescript: latest
  zod: latest

catalogs:
  astro:
    '@astrojs/node': latest
    '@astrojs/react': latest
    '@astrojs/starlight': latest
    '@astrojs/starlight-tailwind': latest
    '@astrojs/ts-plugin': latest
    astro: latest
  dmno:
    '@dmno/astro-integration': latest
    '@dmno/fastify-integration': latest
    dmno: latest
  react19:
    '@types/react': latest
    '@types/react-dom': latest
    react: latest
    react-dom: latest
  tsrest:
    '@ts-rest/core': 3.53.0-rc.1
    '@ts-rest/fastify': 3.53.0-rc.1
    '@ts-rest/open-api': 3.53.0-rc.1
    '@ts-rest/react-query': 3.53.0-rc.1
